**Problems I faced:**
 - I had trouble running the bot. The problem was that I had not activated the virtual environment of python-zulip-api. It was a silly mistake. The error message was `No module named zulip_bots.bots.message_info.test_message_info`.
